require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'derma_dev' do
  config = use_native_modules!

  use_react_native!(
    :path => config["reactNativePath"],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  target 'derma_devTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    # react_native_post_install(installer)
    # __apply_Xcode_12_5_M1_post_install_workaround(installer)
    # installer.pods_project.build_configurations.each do |config|
    #   config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "*"
    # end
  end
end

target 'derma_dev-tvOS' do
  # Pods for derma_dev-tvOS

  target 'derma_dev-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
